### ISSUE TITLE
Compiler Option Enable c++ exceptions

### ISSUE THREAD

**Issue by thiamugb** [nkolban/esp32-snippets#318]
I have a problem when i want to make my project i have this error and i see nothing in the menuconfig help.
Here is my error!!
**In file included from /Users/thiammac/Documents/workspace/cpp3/components/cpp_utils/./BLEClient.h:18:0,
                 from /Users/thiammac/Documents/workspace/cpp3/components/cpp_utils/./BLEScan.h:16,
                 from /Users/thiammac/Documents/workspace/cpp3/components/cpp_utils/./BLEAdvertisedDevice.h:17,
                 from /Users/thiammac/Documents/workspace/cpp3/components/cpp_utils/./BLEAdvertisedDevice.cpp:18:
/Users/thiammac/Documents/workspace/cpp3/components/cpp_utils/./BLEExceptions.h:13:2: error: #error "C++ exception handling must be enabled within make menuconfig. See Compiler Options > Enable C++ Exceptions."
 #error "C++ exception handling must be enabled within make menuconfig. See Compiler Options > Enable C++ Exceptions."
  ^
make[1]: *** [BLEAdvertisedDevice.o] Error 1
make: *** [component-cpp_utils-build] Error 2**
Best regards

**Comment by chegewara** [comment]
Is it arduino-ide or esp-idf?

**Comment by thiamugb** [comment]
Its esp-idf i use eclipse in c++

Cordialement 
Thiam babacar
Contact :+1(514)-951-1353

**Comment by chegewara** [comment]
https://github.com/nkolban/esp32-snippets/issues/231#issuecomment-347039923

**Comment by thiamugb** [comment]
So i see them it’s different!!
In my menuconfig i haven’t c++exception in compiler options

**Comment by chegewara** [comment]
Then you have to update esp-idf

**Comment by thiamugb** [comment]
i update then and after i have an error with this code saying:
 error: 'class BLEServer' has no member named 'setEncryptionLevel'
   pServer->setEncryptionLevel(ESP_BLE_SEC_ENCRYPT_NO_MITM);
            ^

**Comment by chegewara** [comment]
Yes, you have old example. I redesigned lately securit library. Check #313

**Comment by thiamugb** [comment]
Yes i see the error is the new security option.
So what do you want edit file in cpp_utils/BLEclient and server using #313 or delete example test https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLETests/SampleSecureServer.cpp or client.
I am confused!!!!

**Comment by chegewara** [comment]
In #313 i redesigned security but for some reason i didnt delete obsolete files. All new example files are in security subfolder.

**Comment by thiamugb** [comment]
Okay i see.
Me i thought we used just BLETests folder. All is done my test is correct.
thanx see u ... 
When i used server BLE its not easy to see BLE in another periphery ( for example my cellphone) because if i used micro python my BLE is found easily.
Its an configuration or No ,

**Comment by chegewara** [comment]
I dont know what is the issue, i can find anything i flash onto my two esp32-DevKitC devices with no problem. Im using to tests samsung SGS4 and laptop with windows 10.

**Comment by BladeRunner68** [comment]
I'm having major issues with this when trying to compile on Platformio - was there a cure at all?

**Comment by arnopoulos** [comment]
@BladeRunner68 I am also running into the same issue. I was able to wrap the definition and uses of `BLEDisconnectedException` and `BLEUuidNotFoundException` inside of `#if CONFIG_CXX_EXCEPTIONS == 1` blocks. However I hit a roadblock with uses of `esp_bt.h`. I don't know enough about `esp_bt.h` to fix this issue. Which is unfortunate because I need to use `BLEAdvertisementData` for a project I'm working on and that was introduced in `v0.4.8` the same version that introduces the compilation error.

**Comment by arnopoulos** [comment]
@BladeRunner68 I was able to fix this issue by upgrading the platform inside of the PlatformIO Home page. I'm not sure if this will fix the issue for you but it definitely fixed the issue for me.

**Comment by chegewara** [comment]
How about updating arduino environment? Its been enabled long time ago.

**Comment by MikeyMoMo** [comment]
On 1.8.4.  Isn't that new enough?

**Comment by chegewara** [comment]
https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/windows.md#how-to-update-to-the-latest-code
